// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: internal/transport/pb/transfer.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Protocol int32

const (
	Protocol_VERSION_UNSPECIFIED Protocol = 0
	Protocol_VERSION_V1          Protocol = 1
)

// Enum value maps for Protocol.
var (
	Protocol_name = map[int32]string{
		0: "VERSION_UNSPECIFIED",
		1: "VERSION_V1",
	}
	Protocol_value = map[string]int32{
		"VERSION_UNSPECIFIED": 0,
		"VERSION_V1":          1,
	}
)

func (x Protocol) Enum() *Protocol {
	p := new(Protocol)
	*p = x
	return p
}

func (x Protocol) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Protocol) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_transport_pb_transfer_proto_enumTypes[0].Descriptor()
}

func (Protocol) Type() protoreflect.EnumType {
	return &file_internal_transport_pb_transfer_proto_enumTypes[0]
}

func (x Protocol) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Protocol.Descriptor instead.
func (Protocol) EnumDescriptor() ([]byte, []int) {
	return file_internal_transport_pb_transfer_proto_rawDescGZIP(), []int{0}
}

type MessageType int32

const (
	MessageType_MESSAGE_TYPE_UNSPECIFIED MessageType = 0
	MessageType_MESSAGE_TYPE_HELLO       MessageType = 1
	MessageType_MESSAGE_TYPE_HANDSHAKE   MessageType = 2
	MessageType_MESSAGE_TYPE_CHUNK       MessageType = 3
	MessageType_MESSAGE_TYPE_ACK         MessageType = 4
	MessageType_MESSAGE_TYPE_CONTROL     MessageType = 5
	MessageType_MESSAGE_TYPE_DONE        MessageType = 6
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0: "MESSAGE_TYPE_UNSPECIFIED",
		1: "MESSAGE_TYPE_HELLO",
		2: "MESSAGE_TYPE_HANDSHAKE",
		3: "MESSAGE_TYPE_CHUNK",
		4: "MESSAGE_TYPE_ACK",
		5: "MESSAGE_TYPE_CONTROL",
		6: "MESSAGE_TYPE_DONE",
	}
	MessageType_value = map[string]int32{
		"MESSAGE_TYPE_UNSPECIFIED": 0,
		"MESSAGE_TYPE_HELLO":       1,
		"MESSAGE_TYPE_HANDSHAKE":   2,
		"MESSAGE_TYPE_CHUNK":       3,
		"MESSAGE_TYPE_ACK":         4,
		"MESSAGE_TYPE_CONTROL":     5,
		"MESSAGE_TYPE_DONE":        6,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_transport_pb_transfer_proto_enumTypes[1].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_internal_transport_pb_transfer_proto_enumTypes[1]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_internal_transport_pb_transfer_proto_rawDescGZIP(), []int{1}
}

type ControlAction int32

const (
	ControlAction_CONTROL_ACTION_UNSPECIFIED   ControlAction = 0
	ControlAction_CONTROL_ACTION_HANDSHAKE_ACK ControlAction = 1
	ControlAction_CONTROL_ACTION_PAUSE         ControlAction = 2
	ControlAction_CONTROL_ACTION_RESUME        ControlAction = 3
	ControlAction_CONTROL_ACTION_ERROR         ControlAction = 4
)

// Enum value maps for ControlAction.
var (
	ControlAction_name = map[int32]string{
		0: "CONTROL_ACTION_UNSPECIFIED",
		1: "CONTROL_ACTION_HANDSHAKE_ACK",
		2: "CONTROL_ACTION_PAUSE",
		3: "CONTROL_ACTION_RESUME",
		4: "CONTROL_ACTION_ERROR",
	}
	ControlAction_value = map[string]int32{
		"CONTROL_ACTION_UNSPECIFIED":   0,
		"CONTROL_ACTION_HANDSHAKE_ACK": 1,
		"CONTROL_ACTION_PAUSE":         2,
		"CONTROL_ACTION_RESUME":        3,
		"CONTROL_ACTION_ERROR":         4,
	}
)

func (x ControlAction) Enum() *ControlAction {
	p := new(ControlAction)
	*p = x
	return p
}

func (x ControlAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ControlAction) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_transport_pb_transfer_proto_enumTypes[2].Descriptor()
}

func (ControlAction) Type() protoreflect.EnumType {
	return &file_internal_transport_pb_transfer_proto_enumTypes[2]
}

func (x ControlAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ControlAction.Descriptor instead.
func (ControlAction) EnumDescriptor() ([]byte, []int) {
	return file_internal_transport_pb_transfer_proto_rawDescGZIP(), []int{2}
}

type RootEntryType int32

const (
	RootEntryType_ROOT_ENTRY_TYPE_UNSPECIFIED RootEntryType = 0
	RootEntryType_ROOT_ENTRY_TYPE_FILE        RootEntryType = 1
	RootEntryType_ROOT_ENTRY_TYPE_DIRECTORY   RootEntryType = 2
)

// Enum value maps for RootEntryType.
var (
	RootEntryType_name = map[int32]string{
		0: "ROOT_ENTRY_TYPE_UNSPECIFIED",
		1: "ROOT_ENTRY_TYPE_FILE",
		2: "ROOT_ENTRY_TYPE_DIRECTORY",
	}
	RootEntryType_value = map[string]int32{
		"ROOT_ENTRY_TYPE_UNSPECIFIED": 0,
		"ROOT_ENTRY_TYPE_FILE":        1,
		"ROOT_ENTRY_TYPE_DIRECTORY":   2,
	}
)

func (x RootEntryType) Enum() *RootEntryType {
	p := new(RootEntryType)
	*p = x
	return p
}

func (x RootEntryType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RootEntryType) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_transport_pb_transfer_proto_enumTypes[3].Descriptor()
}

func (RootEntryType) Type() protoreflect.EnumType {
	return &file_internal_transport_pb_transfer_proto_enumTypes[3]
}

func (x RootEntryType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RootEntryType.Descriptor instead.
func (RootEntryType) EnumDescriptor() ([]byte, []int) {
	return file_internal_transport_pb_transfer_proto_rawDescGZIP(), []int{3}
}

type PermissionMode int32

const (
	PermissionMode_PERMISSION_MODE_UNSPECIFIED PermissionMode = 0
	PermissionMode_PERMISSION_MODE_NONE        PermissionMode = 1
	PermissionMode_PERMISSION_MODE_PARTIAL     PermissionMode = 2
	PermissionMode_PERMISSION_MODE_ALL         PermissionMode = 3
)

// Enum value maps for PermissionMode.
var (
	PermissionMode_name = map[int32]string{
		0: "PERMISSION_MODE_UNSPECIFIED",
		1: "PERMISSION_MODE_NONE",
		2: "PERMISSION_MODE_PARTIAL",
		3: "PERMISSION_MODE_ALL",
	}
	PermissionMode_value = map[string]int32{
		"PERMISSION_MODE_UNSPECIFIED": 0,
		"PERMISSION_MODE_NONE":        1,
		"PERMISSION_MODE_PARTIAL":     2,
		"PERMISSION_MODE_ALL":         3,
	}
)

func (x PermissionMode) Enum() *PermissionMode {
	p := new(PermissionMode)
	*p = x
	return p
}

func (x PermissionMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PermissionMode) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_transport_pb_transfer_proto_enumTypes[4].Descriptor()
}

func (PermissionMode) Type() protoreflect.EnumType {
	return &file_internal_transport_pb_transfer_proto_enumTypes[4]
}

func (x PermissionMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PermissionMode.Descriptor instead.
func (PermissionMode) EnumDescriptor() ([]byte, []int) {
	return file_internal_transport_pb_transfer_proto_rawDescGZIP(), []int{4}
}

type Message struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Version   int32                  `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Type      MessageType            `protobuf:"varint,2,opt,name=type,proto3,enum=transport.MessageType" json:"type,omitempty"`
	Id        string                 `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"` //transfer id
	SessionId string                 `protobuf:"bytes,4,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*Message_Hello
	//	*Message_Handshake
	//	*Message_Chunk
	//	*Message_Ack
	//	*Message_Resume
	//	*Message_Control
	Payload       isMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_internal_transport_pb_transfer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_internal_transport_pb_transfer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_internal_transport_pb_transfer_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Message) GetType() MessageType {
	if x != nil {
		return x.Type
	}
	return MessageType_MESSAGE_TYPE_UNSPECIFIED
}

func (x *Message) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Message) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *Message) GetPayload() isMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Message) GetHello() *Hello {
	if x != nil {
		if x, ok := x.Payload.(*Message_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *Message) GetHandshake() *Handshake {
	if x != nil {
		if x, ok := x.Payload.(*Message_Handshake); ok {
			return x.Handshake
		}
	}
	return nil
}

func (x *Message) GetChunk() *Chunk {
	if x != nil {
		if x, ok := x.Payload.(*Message_Chunk); ok {
			return x.Chunk
		}
	}
	return nil
}

func (x *Message) GetAck() *Ack {
	if x != nil {
		if x, ok := x.Payload.(*Message_Ack); ok {
			return x.Ack
		}
	}
	return nil
}

func (x *Message) GetResume() *Resume {
	if x != nil {
		if x, ok := x.Payload.(*Message_Resume); ok {
			return x.Resume
		}
	}
	return nil
}

func (x *Message) GetControl() *Control {
	if x != nil {
		if x, ok := x.Payload.(*Message_Control); ok {
			return x.Control
		}
	}
	return nil
}

type isMessage_Payload interface {
	isMessage_Payload()
}

type Message_Hello struct {
	Hello *Hello `protobuf:"bytes,5,opt,name=hello,proto3,oneof"`
}

type Message_Handshake struct {
	Handshake *Handshake `protobuf:"bytes,6,opt,name=handshake,proto3,oneof"`
}

type Message_Chunk struct {
	Chunk *Chunk `protobuf:"bytes,7,opt,name=chunk,proto3,oneof"`
}

type Message_Ack struct {
	Ack *Ack `protobuf:"bytes,8,opt,name=ack,proto3,oneof"`
}

type Message_Resume struct {
	Resume *Resume `protobuf:"bytes,9,opt,name=resume,proto3,oneof"`
}

type Message_Control struct {
	Control *Control `protobuf:"bytes,10,opt,name=control,proto3,oneof"`
}

func (*Message_Hello) isMessage_Payload() {}

func (*Message_Handshake) isMessage_Payload() {}

func (*Message_Chunk) isMessage_Payload() {}

func (*Message_Ack) isMessage_Payload() {}

func (*Message_Resume) isMessage_Payload() {}

func (*Message_Control) isMessage_Payload() {}

type Hello struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Port          int32                  `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	Version       string                 `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	UserName      string                 `protobuf:"bytes,5,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Hello) Reset() {
	*x = Hello{}
	mi := &file_internal_transport_pb_transfer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hello) ProtoMessage() {}

func (x *Hello) ProtoReflect() protoreflect.Message {
	mi := &file_internal_transport_pb_transfer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hello.ProtoReflect.Descriptor instead.
func (*Hello) Descriptor() ([]byte, []int) {
	return file_internal_transport_pb_transfer_proto_rawDescGZIP(), []int{1}
}

func (x *Hello) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Hello) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Hello) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *Hello) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Hello) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

type Handshake struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Roots         []*RootEntry           `protobuf:"bytes,1,rep,name=roots,proto3" json:"roots,omitempty"`
	TotalSize     int64                  `protobuf:"varint,2,opt,name=total_size,json=totalSize,proto3" json:"total_size,omitempty"`
	ChunkSize     int32                  `protobuf:"varint,3,opt,name=chunk_size,json=chunkSize,proto3" json:"chunk_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Handshake) Reset() {
	*x = Handshake{}
	mi := &file_internal_transport_pb_transfer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Handshake) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Handshake) ProtoMessage() {}

func (x *Handshake) ProtoReflect() protoreflect.Message {
	mi := &file_internal_transport_pb_transfer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Handshake.ProtoReflect.Descriptor instead.
func (*Handshake) Descriptor() ([]byte, []int) {
	return file_internal_transport_pb_transfer_proto_rawDescGZIP(), []int{2}
}

func (x *Handshake) GetRoots() []*RootEntry {
	if x != nil {
		return x.Roots
	}
	return nil
}

func (x *Handshake) GetTotalSize() int64 {
	if x != nil {
		return x.TotalSize
	}
	return 0
}

func (x *Handshake) GetChunkSize() int32 {
	if x != nil {
		return x.ChunkSize
	}
	return 0
}

type RootEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type          RootEntryType          `protobuf:"varint,3,opt,name=type,proto3,enum=transport.RootEntryType" json:"type,omitempty"`
	Files         []*FileMeta            `protobuf:"bytes,4,rep,name=files,proto3" json:"files,omitempty"`
	Size          int64                  `protobuf:"varint,5,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RootEntry) Reset() {
	*x = RootEntry{}
	mi := &file_internal_transport_pb_transfer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RootEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RootEntry) ProtoMessage() {}

func (x *RootEntry) ProtoReflect() protoreflect.Message {
	mi := &file_internal_transport_pb_transfer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RootEntry.ProtoReflect.Descriptor instead.
func (*RootEntry) Descriptor() ([]byte, []int) {
	return file_internal_transport_pb_transfer_proto_rawDescGZIP(), []int{3}
}

func (x *RootEntry) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RootEntry) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RootEntry) GetType() RootEntryType {
	if x != nil {
		return x.Type
	}
	return RootEntryType_ROOT_ENTRY_TYPE_UNSPECIFIED
}

func (x *RootEntry) GetFiles() []*FileMeta {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *RootEntry) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type FileMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Size          int64                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	Checksum      string                 `protobuf:"bytes,4,opt,name=checksum,proto3" json:"checksum,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileMeta) Reset() {
	*x = FileMeta{}
	mi := &file_internal_transport_pb_transfer_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileMeta) ProtoMessage() {}

func (x *FileMeta) ProtoReflect() protoreflect.Message {
	mi := &file_internal_transport_pb_transfer_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileMeta.ProtoReflect.Descriptor instead.
func (*FileMeta) Descriptor() ([]byte, []int) {
	return file_internal_transport_pb_transfer_proto_rawDescGZIP(), []int{4}
}

func (x *FileMeta) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *FileMeta) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FileMeta) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *FileMeta) GetChecksum() string {
	if x != nil {
		return x.Checksum
	}
	return ""
}

type Chunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RootId        string                 `protobuf:"bytes,1,opt,name=root_id,json=rootId,proto3" json:"root_id,omitempty"`
	FileId        string                 `protobuf:"bytes,2,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	Index         int32                  `protobuf:"varint,3,opt,name=index,proto3" json:"index,omitempty"`
	Total         int32                  `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	Offset        int64                  `protobuf:"varint,5,opt,name=offset,proto3" json:"offset,omitempty"`
	Size          int64                  `protobuf:"varint,6,opt,name=size,proto3" json:"size,omitempty"`
	Checksum      string                 `protobuf:"bytes,7,opt,name=checksum,proto3" json:"checksum,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Chunk) Reset() {
	*x = Chunk{}
	mi := &file_internal_transport_pb_transfer_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Chunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chunk) ProtoMessage() {}

func (x *Chunk) ProtoReflect() protoreflect.Message {
	mi := &file_internal_transport_pb_transfer_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chunk.ProtoReflect.Descriptor instead.
func (*Chunk) Descriptor() ([]byte, []int) {
	return file_internal_transport_pb_transfer_proto_rawDescGZIP(), []int{5}
}

func (x *Chunk) GetRootId() string {
	if x != nil {
		return x.RootId
	}
	return ""
}

func (x *Chunk) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *Chunk) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *Chunk) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *Chunk) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *Chunk) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *Chunk) GetChecksum() string {
	if x != nil {
		return x.Checksum
	}
	return ""
}

type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileId        string                 `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	Index         int32                  `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	Ok            bool                   `protobuf:"varint,3,opt,name=ok,proto3" json:"ok,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_internal_transport_pb_transfer_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_internal_transport_pb_transfer_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_internal_transport_pb_transfer_proto_rawDescGZIP(), []int{6}
}

func (x *Ack) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *Ack) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *Ack) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *Ack) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type Resume struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileId        string                 `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	Missing       []int32                `protobuf:"varint,2,rep,packed,name=missing,proto3" json:"missing,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Resume) Reset() {
	*x = Resume{}
	mi := &file_internal_transport_pb_transfer_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resume) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resume) ProtoMessage() {}

func (x *Resume) ProtoReflect() protoreflect.Message {
	mi := &file_internal_transport_pb_transfer_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resume.ProtoReflect.Descriptor instead.
func (*Resume) Descriptor() ([]byte, []int) {
	return file_internal_transport_pb_transfer_proto_rawDescGZIP(), []int{7}
}

func (x *Resume) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *Resume) GetMissing() []int32 {
	if x != nil {
		return x.Missing
	}
	return nil
}

type Control struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        ControlAction          `protobuf:"varint,1,opt,name=action,proto3,enum=transport.ControlAction" json:"action,omitempty"`
	Files         []*FileControl         `protobuf:"bytes,2,rep,name=files,proto3" json:"files,omitempty"`
	Mode          PermissionMode         `protobuf:"varint,3,opt,name=mode,proto3,enum=transport.PermissionMode" json:"mode,omitempty"`
	Details       string                 `protobuf:"bytes,4,opt,name=details,proto3" json:"details,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Control) Reset() {
	*x = Control{}
	mi := &file_internal_transport_pb_transfer_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Control) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Control) ProtoMessage() {}

func (x *Control) ProtoReflect() protoreflect.Message {
	mi := &file_internal_transport_pb_transfer_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Control.ProtoReflect.Descriptor instead.
func (*Control) Descriptor() ([]byte, []int) {
	return file_internal_transport_pb_transfer_proto_rawDescGZIP(), []int{8}
}

func (x *Control) GetAction() ControlAction {
	if x != nil {
		return x.Action
	}
	return ControlAction_CONTROL_ACTION_UNSPECIFIED
}

func (x *Control) GetFiles() []*FileControl {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *Control) GetMode() PermissionMode {
	if x != nil {
		return x.Mode
	}
	return PermissionMode_PERMISSION_MODE_UNSPECIFIED
}

func (x *Control) GetDetails() string {
	if x != nil {
		return x.Details
	}
	return ""
}

type FileControl struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileId        string                 `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	Allowed       bool                   `protobuf:"varint,2,opt,name=allowed,proto3" json:"allowed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileControl) Reset() {
	*x = FileControl{}
	mi := &file_internal_transport_pb_transfer_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileControl) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileControl) ProtoMessage() {}

func (x *FileControl) ProtoReflect() protoreflect.Message {
	mi := &file_internal_transport_pb_transfer_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileControl.ProtoReflect.Descriptor instead.
func (*FileControl) Descriptor() ([]byte, []int) {
	return file_internal_transport_pb_transfer_proto_rawDescGZIP(), []int{9}
}

func (x *FileControl) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *FileControl) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

var File_internal_transport_pb_transfer_proto protoreflect.FileDescriptor

const file_internal_transport_pb_transfer_proto_rawDesc = "" +
	"\n" +
	"$internal/transport/pb/transfer.proto\x12\ttransport\"\x94\x03\n" +
	"\aMessage\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x05R\aversion\x12*\n" +
	"\x04type\x18\x02 \x01(\x0e2\x16.transport.MessageTypeR\x04type\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"session_id\x18\x04 \x01(\tR\tsessionId\x12(\n" +
	"\x05hello\x18\x05 \x01(\v2\x10.transport.HelloH\x00R\x05hello\x124\n" +
	"\thandshake\x18\x06 \x01(\v2\x14.transport.HandshakeH\x00R\thandshake\x12(\n" +
	"\x05chunk\x18\a \x01(\v2\x10.transport.ChunkH\x00R\x05chunk\x12\"\n" +
	"\x03ack\x18\b \x01(\v2\x0e.transport.AckH\x00R\x03ack\x12+\n" +
	"\x06resume\x18\t \x01(\v2\x11.transport.ResumeH\x00R\x06resume\x12.\n" +
	"\acontrol\x18\n" +
	" \x01(\v2\x12.transport.ControlH\x00R\acontrolB\t\n" +
	"\apayload\"v\n" +
	"\x05Hello\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04port\x18\x03 \x01(\x05R\x04port\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\x12\x1b\n" +
	"\tuser_name\x18\x05 \x01(\tR\buserName\"u\n" +
	"\tHandshake\x12*\n" +
	"\x05roots\x18\x01 \x03(\v2\x14.transport.RootEntryR\x05roots\x12\x1d\n" +
	"\n" +
	"total_size\x18\x02 \x01(\x03R\ttotalSize\x12\x1d\n" +
	"\n" +
	"chunk_size\x18\x03 \x01(\x05R\tchunkSize\"\x9c\x01\n" +
	"\tRootEntry\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12,\n" +
	"\x04type\x18\x03 \x01(\x0e2\x18.transport.RootEntryTypeR\x04type\x12)\n" +
	"\x05files\x18\x04 \x03(\v2\x13.transport.FileMetaR\x05files\x12\x12\n" +
	"\x04size\x18\x05 \x01(\x03R\x04size\"^\n" +
	"\bFileMeta\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size\x12\x1a\n" +
	"\bchecksum\x18\x04 \x01(\tR\bchecksum\"\xad\x01\n" +
	"\x05Chunk\x12\x17\n" +
	"\aroot_id\x18\x01 \x01(\tR\x06rootId\x12\x17\n" +
	"\afile_id\x18\x02 \x01(\tR\x06fileId\x12\x14\n" +
	"\x05index\x18\x03 \x01(\x05R\x05index\x12\x14\n" +
	"\x05total\x18\x04 \x01(\x05R\x05total\x12\x16\n" +
	"\x06offset\x18\x05 \x01(\x03R\x06offset\x12\x12\n" +
	"\x04size\x18\x06 \x01(\x03R\x04size\x12\x1a\n" +
	"\bchecksum\x18\a \x01(\tR\bchecksum\"Z\n" +
	"\x03Ack\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\tR\x06fileId\x12\x14\n" +
	"\x05index\x18\x02 \x01(\x05R\x05index\x12\x0e\n" +
	"\x02ok\x18\x03 \x01(\bR\x02ok\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\";\n" +
	"\x06Resume\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\tR\x06fileId\x12\x18\n" +
	"\amissing\x18\x02 \x03(\x05R\amissing\"\xb2\x01\n" +
	"\aControl\x120\n" +
	"\x06action\x18\x01 \x01(\x0e2\x18.transport.ControlActionR\x06action\x12,\n" +
	"\x05files\x18\x02 \x03(\v2\x16.transport.FileControlR\x05files\x12-\n" +
	"\x04mode\x18\x03 \x01(\x0e2\x19.transport.PermissionModeR\x04mode\x12\x18\n" +
	"\adetails\x18\x04 \x01(\tR\adetails\"@\n" +
	"\vFileControl\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\tR\x06fileId\x12\x18\n" +
	"\aallowed\x18\x02 \x01(\bR\aallowed*3\n" +
	"\bProtocol\x12\x17\n" +
	"\x13VERSION_UNSPECIFIED\x10\x00\x12\x0e\n" +
	"\n" +
	"VERSION_V1\x10\x01*\xbe\x01\n" +
	"\vMessageType\x12\x1c\n" +
	"\x18MESSAGE_TYPE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12MESSAGE_TYPE_HELLO\x10\x01\x12\x1a\n" +
	"\x16MESSAGE_TYPE_HANDSHAKE\x10\x02\x12\x16\n" +
	"\x12MESSAGE_TYPE_CHUNK\x10\x03\x12\x14\n" +
	"\x10MESSAGE_TYPE_ACK\x10\x04\x12\x18\n" +
	"\x14MESSAGE_TYPE_CONTROL\x10\x05\x12\x15\n" +
	"\x11MESSAGE_TYPE_DONE\x10\x06*\xa0\x01\n" +
	"\rControlAction\x12\x1e\n" +
	"\x1aCONTROL_ACTION_UNSPECIFIED\x10\x00\x12 \n" +
	"\x1cCONTROL_ACTION_HANDSHAKE_ACK\x10\x01\x12\x18\n" +
	"\x14CONTROL_ACTION_PAUSE\x10\x02\x12\x19\n" +
	"\x15CONTROL_ACTION_RESUME\x10\x03\x12\x18\n" +
	"\x14CONTROL_ACTION_ERROR\x10\x04*i\n" +
	"\rRootEntryType\x12\x1f\n" +
	"\x1bROOT_ENTRY_TYPE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14ROOT_ENTRY_TYPE_FILE\x10\x01\x12\x1d\n" +
	"\x19ROOT_ENTRY_TYPE_DIRECTORY\x10\x02*\x81\x01\n" +
	"\x0ePermissionMode\x12\x1f\n" +
	"\x1bPERMISSION_MODE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14PERMISSION_MODE_NONE\x10\x01\x12\x1b\n" +
	"\x17PERMISSION_MODE_PARTIAL\x10\x02\x12\x17\n" +
	"\x13PERMISSION_MODE_ALL\x10\x03B;Z9github.com/Maruf-Hasan1789/peerdrop/internal/transport/pbb\x06proto3"

var (
	file_internal_transport_pb_transfer_proto_rawDescOnce sync.Once
	file_internal_transport_pb_transfer_proto_rawDescData []byte
)

func file_internal_transport_pb_transfer_proto_rawDescGZIP() []byte {
	file_internal_transport_pb_transfer_proto_rawDescOnce.Do(func() {
		file_internal_transport_pb_transfer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_transport_pb_transfer_proto_rawDesc), len(file_internal_transport_pb_transfer_proto_rawDesc)))
	})
	return file_internal_transport_pb_transfer_proto_rawDescData
}

var file_internal_transport_pb_transfer_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_internal_transport_pb_transfer_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_internal_transport_pb_transfer_proto_goTypes = []any{
	(Protocol)(0),       // 0: transport.Protocol
	(MessageType)(0),    // 1: transport.MessageType
	(ControlAction)(0),  // 2: transport.ControlAction
	(RootEntryType)(0),  // 3: transport.RootEntryType
	(PermissionMode)(0), // 4: transport.PermissionMode
	(*Message)(nil),     // 5: transport.Message
	(*Hello)(nil),       // 6: transport.Hello
	(*Handshake)(nil),   // 7: transport.Handshake
	(*RootEntry)(nil),   // 8: transport.RootEntry
	(*FileMeta)(nil),    // 9: transport.FileMeta
	(*Chunk)(nil),       // 10: transport.Chunk
	(*Ack)(nil),         // 11: transport.Ack
	(*Resume)(nil),      // 12: transport.Resume
	(*Control)(nil),     // 13: transport.Control
	(*FileControl)(nil), // 14: transport.FileControl
}
var file_internal_transport_pb_transfer_proto_depIdxs = []int32{
	1,  // 0: transport.Message.type:type_name -> transport.MessageType
	6,  // 1: transport.Message.hello:type_name -> transport.Hello
	7,  // 2: transport.Message.handshake:type_name -> transport.Handshake
	10, // 3: transport.Message.chunk:type_name -> transport.Chunk
	11, // 4: transport.Message.ack:type_name -> transport.Ack
	12, // 5: transport.Message.resume:type_name -> transport.Resume
	13, // 6: transport.Message.control:type_name -> transport.Control
	8,  // 7: transport.Handshake.roots:type_name -> transport.RootEntry
	3,  // 8: transport.RootEntry.type:type_name -> transport.RootEntryType
	9,  // 9: transport.RootEntry.files:type_name -> transport.FileMeta
	2,  // 10: transport.Control.action:type_name -> transport.ControlAction
	14, // 11: transport.Control.files:type_name -> transport.FileControl
	4,  // 12: transport.Control.mode:type_name -> transport.PermissionMode
	13, // [13:13] is the sub-list for method output_type
	13, // [13:13] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_internal_transport_pb_transfer_proto_init() }
func file_internal_transport_pb_transfer_proto_init() {
	if File_internal_transport_pb_transfer_proto != nil {
		return
	}
	file_internal_transport_pb_transfer_proto_msgTypes[0].OneofWrappers = []any{
		(*Message_Hello)(nil),
		(*Message_Handshake)(nil),
		(*Message_Chunk)(nil),
		(*Message_Ack)(nil),
		(*Message_Resume)(nil),
		(*Message_Control)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_transport_pb_transfer_proto_rawDesc), len(file_internal_transport_pb_transfer_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_transport_pb_transfer_proto_goTypes,
		DependencyIndexes: file_internal_transport_pb_transfer_proto_depIdxs,
		EnumInfos:         file_internal_transport_pb_transfer_proto_enumTypes,
		MessageInfos:      file_internal_transport_pb_transfer_proto_msgTypes,
	}.Build()
	File_internal_transport_pb_transfer_proto = out.File
	file_internal_transport_pb_transfer_proto_goTypes = nil
	file_internal_transport_pb_transfer_proto_depIdxs = nil
}
