// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearTransferHistory() {
  return window['go']['app']['App']['ClearTransferHistory']();
}

export function DisconnectPeer(arg1) {
  return window['go']['app']['App']['DisconnectPeer'](arg1);
}

export function GetSettings() {
  return window['go']['app']['App']['GetSettings']();
}

export function GetTransferHistories() {
  return window['go']['app']['App']['GetTransferHistories']();
}

export function HandleConnection(arg1) {
  return window['go']['app']['App']['HandleConnection'](arg1);
}

export function HandshakePermission(arg1, arg2) {
  return window['go']['app']['App']['HandshakePermission'](arg1, arg2);
}

export function ListPeers() {
  return window['go']['app']['App']['ListPeers']();
}

export function Name(arg1) {
  return window['go']['app']['App']['Name'](arg1);
}

export function OnPeerAdded(arg1) {
  return window['go']['app']['App']['OnPeerAdded'](arg1);
}

export function OnPeerRemoved(arg1) {
  return window['go']['app']['App']['OnPeerRemoved'](arg1);
}

export function PickDownloadFolder() {
  return window['go']['app']['App']['PickDownloadFolder']();
}

export function PickFile() {
  return window['go']['app']['App']['PickFile']();
}

export function RegisterSession(arg1) {
  return window['go']['app']['App']['RegisterSession'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['app']['App']['SaveSettings'](arg1);
}

export function SendFileToPeer(arg1, arg2) {
  return window['go']['app']['App']['SendFileToPeer'](arg1, arg2);
}

export function Startup(arg1, arg2, arg3) {
  return window['go']['app']['App']['Startup'](arg1, arg2, arg3);
}
