// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';
import {transport} from '../models';
import {discovery} from '../models';
import {session} from '../models';
import {context} from '../models';

export function ClearTransferHistory():Promise<void>;

export function DisconnectPeer(arg1:string):Promise<void>;

export function GetSettings():Promise<app.Settings>;

export function GetTransferHistories():Promise<Array<app.transferHistory>>;

export function HandleConnection(arg1:transport.Connection):Promise<void>;

export function ListPeers():Promise<Array<discovery.PeerDTO>>;

export function Name(arg1:string):Promise<string>;

export function OnPeerAdded(arg1:discovery.Peer):Promise<void>;

export function OnPeerRemoved(arg1:discovery.Peer):Promise<void>;

export function PickDownloadFolder():Promise<string>;

export function PickFile():Promise<string>;

export function ReceiveFilePermission(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<void>;

export function RegisterSession(arg1:session.PeerSession):Promise<void>;

export function SaveSettings(arg1:app.Settings):Promise<void>;

export function SendFileToPeer(arg1:string,arg2:string):Promise<void>;

export function Startup(arg1:context.Context,arg2:app.Settings):Promise<void>;
