// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {transport} from '../models';
import {discovery} from '../models';
import {session} from '../models';
import {context} from '../models';

export function HandleConnection(arg1:transport.Connection):Promise<void>;

export function ListPeers():Promise<Array<discovery.PeerDTO>>;

export function Name(arg1:string):Promise<string>;

export function OnPeerAdded(arg1:discovery.Peer):Promise<void>;

export function OnPeerRemoved(arg1:discovery.Peer):Promise<void>;

export function PickFile():Promise<string>;

export function RegisterSession(arg1:session.PeerSession):Promise<void>;

export function SendFileToPeer(arg1:string,arg2:string):Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;
